// Code generated by ts-translate. DO NOT EDIT.

package tsx

import (
	_ "embed"

	ts "github.com/wow-look-at-my/go-tree-sitter"
	grammar "github.com/wow-look-at-my/go-tree-sitter/grammars/typescript"
)

//go:embed tables.zst
var tablesBlob []byte

func loadTables() *ts.Language {
	return ts.LoadGrammar("tsx", tablesBlob, grammar.Scanner())
}

func init() { load = loadTables }
