// Code generated by ts-translate. DO NOT EDIT.

package cpp

import (
	_ "embed"

	ts "github.com/wow-look-at-my/go-tree-sitter"
)

//go:embed tables.zst
var tablesBlob []byte

func loadTables() *ts.Language {
	return ts.LoadGrammar("cpp", tablesBlob, scanner{})
}

func init() { load = loadTables }
