package main

import (
	"fmt"
	"strings"
)

// The generated Go is the loader and nothing else: an embed of the table blob,
// and the call that turns it into a language. The grammar itself is data, and it
// travels in the blob beside this file.
func emitLoader(pkg, scanner, scannerPkg string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by ts-translate. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import (\n\t_ \"embed\"\n\n\tts %q\n", runtimeModule)
	if scannerPkg != "" {
		fmt.Fprintf(&b, "\tgrammar %q\n", scannerPkg)
	}
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "//go:embed %s\nvar tablesBlob []byte\n\n", tablesFile)
	fmt.Fprintf(&b, "func loadTables() *ts.Language {\n")
	fmt.Fprintf(&b, "\treturn ts.LoadGrammar(%q, tablesBlob, %s)\n", pkg, scanner)
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func init() { load = loadTables }\n")
	return b.String()
}

const runtimeModule = "github.com/wow-look-at-my/go-tree-sitter"
