package main

import (
	"fmt"
	"strings"
)

// The generated Go is the loader and nothing else: an embed of the table blob,
// and the call that turns it into a language. The grammar itself is data, and it
// travels in the blob beside this file.
// A standalone package has no hand written half, so the accessor is written
// here rather than found beside it.
func emitLoader(pkg, scanner, scannerPkg string, standalone bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by ts-translate. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import (\n\t_ \"embed\"\n")
	if standalone {
		fmt.Fprintf(&b, "\t\"sync\"\n")
	}
	fmt.Fprintf(&b, "\n\tts %q\n", runtimeModule)
	if scannerPkg != "" {
		fmt.Fprintf(&b, "\tgrammar %q\n", scannerPkg)
	}
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "//go:embed %s\nvar tablesBlob []byte\n\n", tablesFile)
	fmt.Fprintf(&b, "func loadTables() *ts.Language {\n")
	fmt.Fprintf(&b, "\treturn ts.LoadGrammar(%q, tablesBlob, %s)\n", pkg, scanner)
	fmt.Fprintf(&b, "}\n\n")
	if !standalone {
		fmt.Fprintf(&b, "func init() { load = loadTables }\n")
		return b.String()
	}
	fmt.Fprintf(&b, "var language = sync.OnceValue(loadTables)\n\n")
	fmt.Fprintf(&b, "// Language returns the grammar, decoding its tables when a parse needs them.\n")
	fmt.Fprintf(&b, "func Language() *ts.Language { return language() }\n")
	return b.String()
}

const runtimeModule = "github.com/wow-look-at-my/go-tree-sitter"
