package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func goIdent(name string) string {
	name = strings.TrimPrefix(name, "ts_")
	parts := strings.Split(name, "_")
	var sb strings.Builder
	for i, part := range parts {
		if part == "" {
			continue
		}
		if i == 0 {
			sb.WriteString(part)
			continue
		}
		sb.WriteString(strings.ToUpper(part[:1]))
		sb.WriteString(part[1:])
	}
	out := sb.String()
	if out == "" {
		out = "value"
	}
	return out
}

func main() {
	pkg := flag.String("package", "", "name of the generated Go package")
	out := flag.String("out", "", "path of the generated Go file")
	flag.Parse()
	if flag.NArg() != 1 || *pkg == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: ts-translate -package NAME -out FILE parser.c")
		os.Exit(2)
	}

	src, err := os.ReadFile(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	file := parseFile(tokenize(src))
	e := &emitter{file: file, sb: &strings.Builder{}, pkg: *pkg}
	e.emitPackage()

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(e.sb.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func (e *emitter) emitPackage() {
	e.printf("// Code generated by ts-translate. DO NOT EDIT.\n\n")
	e.printf("package %s\n\n", e.pkg)
	e.printf("import ts \"github.com/wow-look-at-my/go-tree-sitter\"\n\n")

	e.emitCharacterSets()
	e.emitTables()
	for name, fn := range map[string]string{"ts_lex": "tsLex", "ts_lex_keywords": "tsLexKeywords"} {
		if f, ok := e.file.lexFns[name]; ok {
			e.emitLexFunc(fn, f)
		}
	}
	e.emitLanguage()
}

func (e *emitter) emitCharacterSets() {
	names := map[string]bool{}
	for _, fn := range e.file.lexFns {
		for _, c := range fn.cases {
			for _, st := range c.stmts {
				collectSets(st, names)
			}
		}
	}
	for name := range names {
		d := e.array(name)
		if d == nil {
			panic("missing character set " + name)
		}
		e.emitCharacterSet(goIdent(name), d)
	}
}

func collectSets(st lexStmt, names map[string]bool) {
	switch v := st.(type) {
	case stmtIf:
		collectSetsExpr(v.cond, names)
		for _, inner := range v.then {
			collectSets(inner, names)
		}
	}
}

func collectSetsExpr(e expr, names map[string]bool) {
	switch v := e.(type) {
	case exprSetContains:
		names[v.set] = true
	case exprUnary:
		collectSetsExpr(v.x, names)
	case exprBinary:
		collectSetsExpr(v.l, names)
		collectSetsExpr(v.r, names)
	}
}

func (e *emitter) emitTables() {
	if d := e.array("ts_parse_table"); d != nil {
		rows := e.constant("LARGE_STATE_COUNT")
		cols := e.constant("SYMBOL_COUNT")
		e.emitIntSlice("parseTable", "uint16", scalarSlice2(d, rows, cols))
	}
	if d := e.array("ts_small_parse_table"); d != nil {
		e.emitIntSlice("smallParseTable", "uint16", scalarSlice(d))
	}
	if d := e.array("ts_small_parse_table_map"); d != nil {
		e.emitIntSlice("smallParseTableMap", "uint32", scalarSlice(d))
	}
	if d := e.array("ts_parse_actions"); d != nil {
		e.emitParseActions("parseActions", d)
	}
	if d := e.array("ts_symbol_names"); d != nil {
		e.emitStringSlice("symbolNames", d)
	}
	if d := e.array("ts_field_names"); d != nil {
		e.emitStringSlice("fieldNames", d)
	}
	if d := e.array("ts_field_map_slices"); d != nil {
		e.emitMapSlices("fieldMapSlices", d)
	}
	if d := e.array("ts_field_map_entries"); d != nil {
		e.emitFieldMapEntries("fieldMapEntries", d)
	}
	if d := e.array("ts_symbol_metadata"); d != nil {
		e.emitSymbolMetadata("symbolMetadata", d)
	}
	if d := e.array("ts_symbol_map"); d != nil {
		e.emitIntSlice("publicSymbolMap", "ts.Symbol", scalarSlice(d))
	}
	if d := e.array("ts_non_terminal_alias_map"); d != nil {
		e.emitIntSlice("aliasMap", "uint16", scalarSlice(d))
	}
	if d := e.array("ts_alias_sequences"); d != nil {
		rows := e.constant("PRODUCTION_ID_COUNT")
		cols := e.constant("MAX_ALIAS_SEQUENCE_LENGTH")
		e.emitIntSlice("aliasSequences", "ts.Symbol", scalarSlice2(d, rows, cols))
	}
	if d := e.array("ts_lex_modes"); d != nil {
		e.emitLexModes("lexModes", d)
	}
	if d := e.array("ts_primary_state_ids"); d != nil {
		e.emitIntSlice("primaryStateIDs", "ts.StateID", scalarSlice(d))
	}
	if d := e.array("ts_reserved_words"); d != nil {
		rows := dimension(d, 0)
		cols := e.constant("MAX_RESERVED_WORD_SET_SIZE")
		e.emitIntSlice("reservedWords", "ts.Symbol", scalarSlice2(d, rows, cols))
	}
	if d := e.array("ts_supertype_symbols"); d != nil {
		e.emitIntSlice("supertypeSymbols", "ts.Symbol", scalarSlice(d))
	}
	if d := e.array("ts_supertype_map_slices"); d != nil {
		e.emitMapSlices("supertypeMapSlices", d)
	}
	if d := e.array("ts_supertype_map_entries"); d != nil {
		e.emitIntSlice("supertypeMapEntries", "ts.Symbol", scalarSlice(d))
	}
	if d := e.array("ts_external_scanner_symbol_map"); d != nil {
		e.emitIntSlice("externalScannerSymbolMap", "ts.Symbol", scalarSlice(d))
	}
	if d := e.array("ts_external_scanner_states"); d != nil {
		rows := dimension(d, 0)
		cols := e.constant("EXTERNAL_TOKEN_COUNT")
		values := scalarSlice2(d, rows, cols)
		e.printf("var externalScannerStates = []bool{")
		for i, v := range values {
			if i%16 == 0 {
				e.printf("\n\t")
			}
			e.printf("%t, ", v != 0)
		}
		e.printf("\n}\n\n")
	}
}

var languageFields = map[string]string{
	"abi_version":               "ABIVersion",
	"symbol_count":              "SymbolCount",
	"alias_count":               "AliasCount",
	"token_count":               "TokenCount",
	"external_token_count":      "ExternalTokenCount",
	"state_count":               "StateCount",
	"large_state_count":         "LargeStateCount",
	"production_id_count":       "ProductionIDCount",
	"field_count":               "FieldCount",
	"supertype_count":           "SupertypeCount",
	"max_alias_sequence_length": "MaxAliasSequenceLen",
	"max_reserved_word_set_size": "MaxReservedWordSetLen",
	"keyword_capture_token":     "KeywordCaptureToken",
}

var languageRefs = map[string]string{
	"parse_table":          "ParseTable",
	"small_parse_table":    "SmallParseTable",
	"small_parse_table_map": "SmallParseTableMap",
	"parse_actions":        "ParseActions",
	"symbol_names":         "SymbolNames",
	"field_names":          "FieldNames",
	"field_map_slices":     "FieldMapSlices",
	"field_map_entries":    "FieldMapEntries",
	"symbol_metadata":      "SymbolMetadataTable",
	"public_symbol_map":    "PublicSymbolMap",
	"alias_map":            "AliasMap",
	"alias_sequences":      "AliasSequences",
	"lex_modes":            "LexModes",
	"primary_state_ids":    "PrimaryStateIDs",
	"reserved_words":       "ReservedWords",
	"supertype_symbols":    "SupertypeSymbols",
	"supertype_map_slices": "SupertypeMapSlices",
	"supertype_map_entries": "SupertypeMapEntries",
}

var refToGoVar = map[string]string{
	"ts_parse_table":                 "parseTable",
	"ts_small_parse_table":           "smallParseTable",
	"ts_small_parse_table_map":       "smallParseTableMap",
	"ts_parse_actions":               "parseActions",
	"ts_symbol_names":                "symbolNames",
	"ts_field_names":                 "fieldNames",
	"ts_field_map_slices":            "fieldMapSlices",
	"ts_field_map_entries":           "fieldMapEntries",
	"ts_symbol_metadata":             "symbolMetadata",
	"ts_symbol_map":                  "publicSymbolMap",
	"ts_non_terminal_alias_map":      "aliasMap",
	"ts_alias_sequences":             "aliasSequences",
	"ts_lex_modes":                   "lexModes",
	"ts_primary_state_ids":           "primaryStateIDs",
	"ts_reserved_words":              "reservedWords",
	"ts_supertype_symbols":           "supertypeSymbols",
	"ts_supertype_map_slices":        "supertypeMapSlices",
	"ts_supertype_map_entries":       "supertypeMapEntries",
	"ts_external_scanner_symbol_map": "externalScannerSymbolMap",
	"ts_external_scanner_states":     "externalScannerStates",
}

func (e *emitter) emitLanguage() {
	e.printf("var language = ts.Language{\n")
	for cField, goField := range languageFields {
		if v, ok := e.file.lang[cField]; ok && v.isNum {
			e.printf("\t%s: %d,\n", goField, v.num)
		}
	}
	for cField, goField := range languageRefs {
		v, ok := e.file.lang[cField]
		if !ok || v.ref == "" {
			continue
		}
		goVar, ok := refToGoVar[v.ref]
		if !ok || e.array(v.ref) == nil {
			continue
		}
		e.printf("\t%s: %s,\n", goField, goVar)
	}
	if v, ok := e.file.lang["name"]; ok && v.isStr {
		e.printf("\tName: %q,\n", v.str)
	}
	if _, ok := e.file.lexFns["ts_lex"]; ok {
		e.printf("\tLexFn: tsLex,\n")
	}
	if _, ok := e.file.lexFns["ts_lex_keywords"]; ok {
		e.printf("\tKeywordLexFn: tsLexKeywords,\n")
	}
	if e.array("ts_external_scanner_states") != nil {
		e.printf("\tExternalScannerStates: externalScannerStates,\n")
	}
	if e.array("ts_external_scanner_symbol_map") != nil {
		e.printf("\tExternalScannerSymbol: externalScannerSymbolMap,\n")
	}
	if v, ok := e.file.lang["metadata"]; ok && v.elems != nil {
		e.printf("\tMetadata: ts.LanguageMetadata{MajorVersion: %d, MinorVersion: %d, PatchVersion: %d},\n",
			v.elems["major_version"], v.elems["minor_version"], v.elems["patch_version"])
	}
	e.printf("}\n\n")

	e.printf("// Language returns the %s grammar.\n", e.file.languageName)
	e.printf("func Language() *ts.Language {\n")
	if e.file.hasScanner {
		e.printf("\tlanguage.Scanner = scanner{}\n")
	}
	e.printf("\treturn &language\n")
	e.printf("}\n")
}
