// Command ts-translate turns a tree-sitter generated parser.c into a Go
// package. The data tables become a compressed blob the package embeds, and the
// lexer state machines become Go functions.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	ts "github.com/wow-look-at-my/go-tree-sitter"
)

// tablesFile is the compressed table blob the generated package embeds.
const tablesFile = "tables.zst"

func main() {
	pkg := flag.String("package", "", "name of the generated Go package")
	out := flag.String("out", "", "path of the generated Go file")
	standalone := flag.Bool("standalone", false,
		"emit Language and its lazy decode, for a package with no hand written half")
	scanner := flag.String("scanner", "",
		"import path of the package whose Scanner the grammar needs")
	flag.Parse()
	if flag.NArg() != 1 || *pkg == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: ts-translate -package NAME -out FILE parser.c")
		os.Exit(2)
	}

	src, err := os.ReadFile(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	file := parseFile(tokenize(src))
	e := &emitter{
		file: file, sb: &strings.Builder{}, pkg: *pkg,
		standalone: *standalone, scannerPkg: *scanner,
	}
	tables := e.buildTables()
	if err := checkABI(tables.Language.ABIVersion); err != nil {
		fmt.Fprintf(os.Stderr, "%s: %v\n", flag.Arg(0), err)
		os.Exit(1)
	}
	blob, err := ts.EncodeTables(tables)
	if err != nil {
		fmt.Fprintln(os.Stderr, "encoding the tables:", err)
		os.Exit(1)
	}
	e.emitPackage()

	dir := filepath.Dir(*out)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(dir, tablesFile), blob, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(e.sb.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("%s: %s is %d bytes, %s is %d bytes\n",
		*pkg, tablesFile, len(blob), filepath.Base(*out), e.sb.Len())
}

func (e *emitter) emitPackage() {
	e.printf("// Code generated by ts-translate. DO NOT EDIT.\n\n")
	e.printf("package %s\n\n", e.pkg)
	e.printf("import (\n\t_ \"embed\"\n")
	if e.standalone {
		e.printf("\t\"sync\"\n")
	}
	e.printf("\n\tts \"github.com/wow-look-at-my/go-tree-sitter\"\n")
	if e.scannerPkg != "" {
		e.printf("\tgrammar %q\n", e.scannerPkg)
	}
	e.printf(")\n\n")
	e.printf("//go:embed %s\n", tablesFile)
	e.printf("var tablesBlob []byte\n\n")
	e.printf("var characterSets [][]ts.CharacterRange\n\n")

	for _, pair := range [][2]string{{"ts_lex", "tsLex"}, {"ts_lex_keywords", "tsLexKeywords"}} {
		if f, ok := e.file.lexFns[pair[0]]; ok {
			e.emitLexFunc(pair[1], f)
		}
	}
	e.emitInit()
}

// emitInit writes the decode step. Language runs it when a parse needs it, so a
// program that never touches this grammar decodes nothing. A blob that will not
// decode panics with the package name, rather than hand back a language that
// parses nothing.
func (e *emitter) emitInit() {
	e.printf("func loadTables() *ts.Language {\n")
	e.printf("\ttables, err := ts.DecodeTables(tablesBlob)\n")
	e.printf("\tif err != nil {\n")
	e.printf("\t\tpanic(%q + err.Error())\n", e.pkg+": reading "+tablesFile+": ")
	e.printf("\t}\n")
	e.printf("\tcharacterSets = tables.CharacterSets\n")
	e.printf("\tlanguage := &tables.Language\n")
	if _, ok := e.file.lexFns["ts_lex"]; ok {
		e.printf("\tlanguage.LexFn = tsLex\n")
	}
	if _, ok := e.file.lexFns["ts_lex_keywords"]; ok {
		e.printf("\tlanguage.KeywordLexFn = tsLexKeywords\n")
	}
	if e.file.hasScanner {
		if e.scannerPkg != "" {
			e.printf("\tlanguage.Scanner = grammar.Scanner()\n")
		} else {
			e.printf("\tlanguage.Scanner = scanner{}\n")
		}
	}
	e.printf("\treturn language\n")
	e.printf("}\n\n")

	if !e.standalone {
		// This assignment is all that runs at package start.
		e.printf("func init() { load = loadTables }\n")
		return
	}
	e.emitLanguage()
}

// emitLanguage writes the accessor a standalone package needs, with the lazy
// decode a hand written half would otherwise supply.
func (e *emitter) emitLanguage() {
	e.printf("var (\n\tloadOnce  sync.Once\n\tgenerated *ts.Language\n)\n\n")
	e.printf("// Language returns the %s grammar, decoding its tables when a\n", e.pkg)
	e.printf("// parse needs them.\n")
	e.printf("func Language() *ts.Language {\n")
	e.printf("\tloadOnce.Do(func() { generated = loadTables() })\n")
	e.printf("\treturn generated\n")
	e.printf("}\n")
}

func collectSets(st lexStmt, names map[string]bool) {
	switch v := st.(type) {
	case stmtIf:
		collectSetsExpr(v.cond, names)
		for _, inner := range v.then {
			collectSets(inner, names)
		}
	}
}

func collectSetsExpr(e expr, names map[string]bool) {
	switch v := e.(type) {
	case exprSetContains:
		names[v.set] = true
	case exprUnary:
		collectSetsExpr(v.x, names)
	case exprBinary:
		collectSetsExpr(v.l, names)
		collectSetsExpr(v.r, names)
	}
}
