// Command ts-translate turns a tree-sitter generated parser.c into a Go
// package. The data tables become a compressed blob the package embeds, and the
// lexer state machines become Go functions.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	ts "github.com/wow-look-at-my/go-tree-sitter"
)

// tablesFile is the compressed table blob the generated package embeds.
const tablesFile = "tables.zst"

func main() {
	pkg := flag.String("package", "", "name of the generated Go package")
	out := flag.String("out", "", "path of the generated Go file")
	flag.Parse()
	if flag.NArg() != 1 || *pkg == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: ts-translate -package NAME -out FILE parser.c")
		os.Exit(2)
	}

	src, err := os.ReadFile(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	file := parseFile(tokenize(src))
	e := &emitter{file: file, sb: &strings.Builder{}, pkg: *pkg}
	blob, err := ts.EncodeTables(e.buildTables())
	if err != nil {
		fmt.Fprintln(os.Stderr, "encoding the tables:", err)
		os.Exit(1)
	}
	e.emitPackage()

	dir := filepath.Dir(*out)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(dir, tablesFile), blob, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(e.sb.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("%s: %s is %d bytes, %s is %d bytes\n",
		*pkg, tablesFile, len(blob), filepath.Base(*out), e.sb.Len())
}

func (e *emitter) emitPackage() {
	e.printf("// Code generated by ts-translate. DO NOT EDIT.\n\n")
	e.printf("package %s\n\n", e.pkg)
	e.printf("import (\n\t_ \"embed\"\n\n")
	e.printf("\tts \"github.com/wow-look-at-my/go-tree-sitter\"\n)\n\n")
	e.printf("//go:embed %s\n", tablesFile)
	e.printf("var tablesBlob []byte\n\n")
	e.printf("var characterSets [][]ts.CharacterRange\n\n")

	for _, pair := range [][2]string{{"ts_lex", "tsLex"}, {"ts_lex_keywords", "tsLexKeywords"}} {
		if f, ok := e.file.lexFns[pair[0]]; ok {
			e.emitLexFunc(pair[1], f)
		}
	}
	e.emitInit()
}

// emitInit writes the decode step. A blob that will not decode panics with the
// package name, rather than register a language that parses nothing.
func (e *emitter) emitInit() {
	e.printf("func init() {\n")
	e.printf("\ttables, err := ts.DecodeTables(tablesBlob)\n")
	e.printf("\tif err != nil {\n")
	e.printf("\t\tpanic(%q + err.Error())\n", e.pkg+": reading "+tablesFile+": ")
	e.printf("\t}\n")
	e.printf("\tcharacterSets = tables.CharacterSets\n")
	e.printf("\tlanguage := &tables.Language\n")
	if _, ok := e.file.lexFns["ts_lex"]; ok {
		e.printf("\tlanguage.LexFn = tsLex\n")
	}
	if _, ok := e.file.lexFns["ts_lex_keywords"]; ok {
		e.printf("\tlanguage.KeywordLexFn = tsLexKeywords\n")
	}
	if e.file.hasScanner {
		e.printf("\tlanguage.Scanner = scanner{}\n")
	}
	e.printf("\tgenerated = language\n")
	e.printf("}\n")
}

func collectSets(st lexStmt, names map[string]bool) {
	switch v := st.(type) {
	case stmtIf:
		collectSetsExpr(v.cond, names)
		for _, inner := range v.then {
			collectSets(inner, names)
		}
	}
}

func collectSetsExpr(e expr, names map[string]bool) {
	switch v := e.(type) {
	case exprSetContains:
		names[v.set] = true
	case exprUnary:
		collectSetsExpr(v.x, names)
	case exprBinary:
		collectSetsExpr(v.l, names)
		collectSetsExpr(v.r, names)
	}
}
